"""持久化仓库端口。应用层只依赖协议，具体适配器在 persistence 中提供。"""

from __future__ import annotations

from typing import Protocol

from .records import AssumptionRecord, BatchRecord, CommitmentRecord


class PortfolioRepository(Protocol):
    def save_assumption(self, record: AssumptionRecord) -> None: ...

    def get_assumption(self, version_id: str) -> AssumptionRecord | None: ...

    def find_assumption_by_digest(self, digest: str) -> AssumptionRecord | None: ...

    def list_assumptions(self) -> list[AssumptionRecord]: ...

    def save_commitment(self, record: CommitmentRecord) -> None: ...

    def list_commitments(self, version_id: str) -> list[CommitmentRecord]: ...

    def save_batch(self, record: BatchRecord) -> None: ...

    def get_batch(self, batch_id: str) -> BatchRecord | None: ...

    def list_batches(self) -> list[BatchRecord]: ...
